/*
 * generated by Xtext
 */
package org.xtext.example.markdown.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MarkdownUiModule extends org.xtext.example.markdown.ui.AbstractMarkdownUiModule {
	public MarkdownUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
