/*
 * generated by Xtext
 */
package org.xtext.example.markdown.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.markdown.ui.internal.MarkdownActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MarkdownExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MarkdownActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MarkdownActivator.getInstance().getInjector(MarkdownActivator.ORG_XTEXT_EXAMPLE_MARKDOWN_MARKDOWN);
	}
	
}
