/**
 * generated by Xtext
 */
package org.xtext.example.markdown.ui.contentassist;

import org.xtext.example.markdown.ui.contentassist.AbstractMarkdownProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MarkdownProposalProvider extends AbstractMarkdownProposalProvider {
}
