/**
 * generated by Xtext
 */
package org.xtext.example.markdown.validation;

import org.xtext.example.markdown.validation.AbstractMarkdownValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MarkdownValidator extends AbstractMarkdownValidator {
}
