/*
 * generated by Xtext
 */
package org.xtext.example.markdown.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.markdown.services.MarkdownGrammarAccess;

@SuppressWarnings("all")
public class MarkdownSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MarkdownGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Content_NEWLINETerminalRuleCall_1_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MarkdownGrammarAccess) access;
		match_Content_NEWLINETerminalRuleCall_1_p = new TokenAlias(true, false, grammarAccess.getContentAccess().getNEWLINETerminalRuleCall_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getNEWLINERule())
			return getNEWLINEToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal NEWLINE:
	 *     '\r'? '\n'
	 * ;
	 */
	protected String getNEWLINEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\n";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Content_NEWLINETerminalRuleCall_1_p.equals(syntax))
				emit_Content_NEWLINETerminalRuleCall_1_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     NEWLINE+
	 *
	 * This ambiguous syntax occurs at:
	 *     entity+=Bold (ambiguity) (rule end)
	 *     entity+=Header1 (ambiguity) (rule end)
	 *     entity+=Header2 (ambiguity) (rule end)
	 *     entity+=Italic (ambiguity) (rule end)
	 *     entity+=PlainText (ambiguity) (rule end)
	 */
	protected void emit_Content_NEWLINETerminalRuleCall_1_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
