/*
 * generated by Xtext
 */
package org.xtext.example.markdown;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MarkdownRuntimeModule extends org.xtext.example.markdown.AbstractMarkdownRuntimeModule {

}
