/*
 * generated by Xtext
 */
package org.xtext.example.markdown;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MarkdownStandaloneSetup extends MarkdownStandaloneSetupGenerated{

	public static void doSetup() {
		new MarkdownStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

